### ISSUE TITLE
Error on deploy

### ISSUE THREAD

**Issue by treeder** [gochain-io/web3-cli#10]
```
$ ./web3-cli contract deploy MyToken.bin
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.(*RPCClient).DeployContract(0xc00000d840, 0x0, 0x0, 0xc00002ec00, 0x396, 0x396, 0x0, 0x7754bc)
        /home/treeder/dev/gochain-io/web3-cli/gochain.go:59 +0x796
main.DeploySol(0xc000026058, 0x7, 0x0, 0x0, 0x0, 0x0, 0x7ffd51ae2b33, 0xb)
        /home/treeder/dev/gochain-io/web3-cli/main.go:278 +0x25a
main.main.func5(0xc0001fe840)
```

I hadn't set my private key or anything yet, on purpose to try to see what errors come back.

**Comment by jmank88** [comment]
Fixed by #11
